package ExceptionHandling;
import java.util.Scanner;

public class Exception
{
    public static void main(String args[])
    {
        int num1,num2,result;
        Scanner sc=new Scanner(System.in);
        try
        {
            System.out.println("Enter First number:");
            num1 = Integer.parseInt(sc.next());
            System.out.println("Enter Second number:");
            num2 = Integer.parseInt(sc.next());
            result=num1/num2;
            System.out.println("Division is:"+result);
            int x[]= new int[12];
            x[15]=60;

        }
        catch(ArithmeticException e)
        {
            System.out.println(e);
        }
        catch(NumberFormatException e)
        {
            System.out.println(e);
        }
        catch (ArrayIndexOutOfBoundsException e)
        {
            System.out.println(e);
        }
    }

}














